### ISSUE TITLE
denseblock写的有问题

### ISSUE THREAD

**Issue by qd213618** [yxlijun/Pelee.Pytorch#1]
原文denseblock里面不应该重复transition层吧，你的循环生成denseblock里面重复了transition，在用你的代码训练目标检测的时候效果不是很好，我改yolo做的就不是很成功。不知道你对这个模块是怎么理解的？重复transition能提高精度么？

**Comment by yxlijun** [comment]
写得有问题吗，我是参照作者https://github.com/Robert-JunWang/PeleeNet 写的

**Comment by qd213618** [comment]
不好意思，在下看错了，仔细看了下确实是没问题
