### ISSUE TITLE
How can I train pelee with custom dataset?

### ISSUE THREAD

**Issue by cnr0724** [yxlijun/Pelee.Pytorch#18]
What should I change?

**Comment by FA78DWA** [comment]
First, you should but you dataset in a VOC-like format. 
Then, go to `configs/Pelee_VOC.py`  and change the following:
* num_classes
* home and VOCroot directories at the very end of the file.

Then, go to `data/voc0712` and change the VOC_CLASSES tuple to your classes.
This should train the model on your data with the default configuration.

**Comment by cnr0724** [comment]
Thanks, FA78DWA! Although I have another error now, at least I can start training process!
