### ISSUE TITLE
What is this line for? Why you didn't use the output of branch2c?

### ISSUE THREAD

**Issue by Sephirot1st** [yxlijun/Pelee.Pytorch#8]
https://github.com/yxlijun/Pelee.Pytorch/blob/1eab4106330f275ab3c5dfb910ddd79a5bac95ef/peleenet.py#L75
As mentioned above, did you do this on purpose? 
Does the pretrained weights you provided trained with this  modification?

**Comment by xlighting** [comment]
It's a bug, I fixed it and retrained the model, got mAP of  72.97%
